
export const ImagesPath = {
    VectorIMG: require(`../../Assets/Images/img.png`),
    TaskIMG: require(`../../Assets/Images/task.jpeg`),
    BackIc: require(`../../Assets/Images/back.png`),
    UserIc: require(`../../Assets/Images/user.png`),
    EyeIc: require(`../../Assets/Images/eye.png`),
    LockIC: require(`../../Assets/Images/lock.png`),
    MailIC: require(`../../Assets/Images/mail.png`),
    MenuIC: require(`../../Assets/Images/menu.png`),
    SearchIC: require(`../../Assets/Images/search.png`),
    ProfileIMG: require(`../../Assets/Images/profile.png`),
    MemberIc: require(`../../Assets/Images/member.png`),
    ProIc: require(`../../Assets/Images/pro.png`),
    ReportIc: require(`../../Assets/Images/report.png`),
    SettingIc: require(`../../Assets/Images/settings.png`),
    LogoutIc: require(`../../Assets/Images/logout.png`),
    ListIc: require(`../../Assets/Images/list.png`),
    FileIc: require(`../../Assets/Images/files.png`),
    AddIc: require(`../../Assets/Images/add.png`),
    SendIc: require(`../../Assets/Images/send.png`),
    SendIc: require(`../../Assets/Images/send.png`),
    UserIcon: require(`../../Assets/Images/users.png`),
    SearchIn: require(`../../Assets/Images/search.png`),
    DotIc: require(`../../Assets/Images/dots.png`),
    CalenderIc: require(`../../Assets/Images/calendar.png`),
    OnGoingIc: require(`../../Assets/Images/ongoing.png`),
    InProgressIc: require(`../../Assets/Images/Inprogress.png`),
    CompleteIc: require(`../../Assets/Images/complete.png`),
    CancelIc: require(`../../Assets/Images/cancel.png`),
    CheckIc: require(`../../Assets/Images/checkbox.png`),
    ChatProfileIMG: require(`../../Assets/Images/ChatProfile.jpeg`),
    MessageIc: require(`../../Assets/Images/message.png`),
    AssignIc: require(`../../Assets/Images/assign.png`),
}