export const NavString={
        SELECTAUTHSCREEN:`SELECTAUTHSCREEN`,
        LOGINSCREEN:'LOGINSCREEN',
        REGISTERSCREEN:`REGISTERSCREEN`,
        PROFILESCREEN:`PROFILESCREEN`,
        BOTTOMTAB:`BOTTOMTAB`,
        PROJECTSCREEN:'PROJECTSCREEN',
        USERHOMESCREEN:`USERHOMESCREEN`,
        LISTSCREEN:'LISTSCREEN',
        CHATSCREEN:`CHATSCREEN`,
        OVERVIEWSCREEN:'OVERVIEWSCREEN'
}